[project]
name = "the-doomsday-algorithm"
version = "1.0.0"
requires-python= ">=3.10"
dependencies = [
    "gatorgrade",
    "mypy>=1.19.1",
    "pytest",
]

[tool.pytest]
testpaths = [
    "tests"
]
